-- Alternative: Use Supabase Database Webhooks (Recommended - Easier Setup)
-- 
-- Instead of using a database trigger, you can set up a webhook in Supabase Dashboard:
--
-- 1. Go to Supabase Dashboard → Database → Webhooks
-- 2. Click "Create a new webhook"
-- 3. Configure:
--    - Name: "Send Push Notification on Event"
--    - Table: events
--    - Events: INSERT
--    - HTTP Request:
--      - URL: https://tnixwhvzkfupsjzobzzt.supabase.co/functions/v1/send-push-notification
--      - Method: POST
--      - Headers:
--        - Authorization: Bearer YOUR_SERVICE_ROLE_KEY
--        - Content-Type: application/json
--      - Body (JSON):
--        {
--          "event_id": "{{ $1.id }}",
--          "user_id": "{{ $1.partner_id }}",
--          "title": "{{ $1.title }}",
--          "event_date": "{{ $1.event_date }}",
--          "event_time": "{{ $1.event_time }}",
--          "created_by": "{{ $1.created_by }}"
--        }
--    - Filter: Only trigger when partner_id is not null and created_by != partner_id
--
-- This is easier than the database trigger approach and doesn't require pg_net extension.

